"""create table

Revision ID: c5ccf3211a82
Revises: 
Create Date: 2025-03-19 22:05:05.806637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ccf3211a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_product_id', sa.String(), nullable=False),
    sa.Column('exchange_product_name', sa.String(), nullable=False),
    sa.Column('oil_id', sa.String(), nullable=False),
    sa.Column('delivery_basis_id', sa.String(), nullable=False),
    sa.Column('delivery_basis_name', sa.String(), nullable=False),
    sa.Column('delivery_type_id', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('updated_on', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
